# Generated by Django 3.2.5 on 2021-09-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_raised',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
