# Generated by Django 3.2.5 on 2021-09-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_total_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.JSONField(default=list),
        ),
    ]
